### ISSUE TITLE
Excessive stack usage for "Disable AMPDU RX on the ESP32 WiFi to fix a bug on Android"

### ISSUE THREAD

**Issue by EmbeddedDevver** [CDFER/Captive-Test#10]
Applying this code below will increase the stack usage by 40k. That is more than 10% of the entire available stack.
 I think it is better to remove it or have it optional.

```
	// Disable AMPDU RX on the ESP32 WiFi to fix a bug on Android
	esp_wifi_stop();
	esp_wifi_deinit();
	wifi_init_config_t my_config = WIFI_INIT_CONFIG_DEFAULT();
	my_config.ampdu_rx_enable = false;
	esp_wifi_init(&my_config);
	esp_wifi_start();
```

**Comment by CDFER** [comment]
After thinking about this for a few days, I'm going to leave the code (it fixes quite a few different android phones) but I'll add a comment to the code explaining this. I think that most projects on the esp32 have more than enough ram to spare (except when caching a large display buffer but then you should be looking at chips with psram). But thanks for bringing this up :)

https://github.com/CDFER/Captive-Portal-ESP32/commit/8b9a175096286fd03606ebe7eafdc8d3b835a56c

**Comment by EmbeddedDevver** [comment]
Totally understand your decision.

In my case the stack went down quickly because of using SSL HTTP Get request that uses about 30% of the stack.

Then the Hotspot including this bug fix used another 30% (async webpage plus hotspot) 

And the Esp32 doesn't work well below 80k of stack on the long run. 

 So in my case I need every piece of stack to maintain a long and stable Esp32
